### ISSUE TITLE
Should we integrate Strong Binding?

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#101]
I believe that is a reference to this paper:
* https://eprint.iacr.org/2020/1525

**Comment by ounsworth** [comment]
At this point we should not change the wire format (cause that will break hackathon artifacts and stuff), but we should at least cite this paper and discuss it in an ednote.

**Comment by johngray-dev** [comment]
We added stronger binding, and now concatenate the OID with the message to give it a weak non-separability property.
