### ISSUE TITLE
Composite Parameters Encoding Issue: Abstraction Layer Violation

### ISSUE THREAD

**Issue by opencrypto** [EntrustCorporation/draft-ounsworth-composite-sigs#106]
There seems to be an high-level abstract layer violation when dealing with the parameters. The current approach mandates for parameters to be a sequence of AlgorithmIdentifiers:
```
sa-CompositeSignature SIGNATURE-ALGORITHM ::= {
    IDENTIFIER id-alg-composite
    VALUE CompositeSignatureValue
    PARAMS TYPE CompositeParams ARE required
    PUBLIC-KEYS { pk-Composite }
    SMIME-CAPS { IDENTIFIED BY id-alg-composite } }
}

CompositeParams ::= SEQUENCE SIZE (2..MAX) OF AlgorithmIdentifier

CompositeSignatureValue ::= SEQUENCE SIZE (2..MAX) OF BIT STRING
```
This works well when operating at the ASN1 layer, but there is a complication. When going into the signature generation/validation, access to the CompositeParams might be difficutlt. Especially, it might not be there if you are signing a non ASN1 structure.

**PROPOSED RESOLUTION:** 

The proposal is to bring the parameters at the layer when they are generated - thus putting the signature and the related parameters together. The resulting structure would be the same, but we would need a change in the parameters' structure:
```
sa-CompositeSignature SIGNATURE-ALGORITHM ::= {
    IDENTIFIER id-alg-composite
    VALUE CompositeSignatureValue
    PARAMS ARE absent
    PUBLIC-KEYS { pk-Composite }
    SMIME-CAPS { IDENTIFIED BY id-alg-composite } }
}

CompositeSignatureValue ::= SEQUENCE SIZE (2..MAX) OF digitalSignature

digitalSignature ::= SEQUENCE {
    algorithm         AlgorithmIdentifier,
    signature         BIT STRING
}
```
This addressed the fact that the parameters for the inner components are generated when the individual component's signature is being generated. That means that we are already at the lower layer. This proposal would allow to generate and store the parameters for the inner components in the BITSTRING content directly, thus allowing to sign non-X509 structures (and be able to validate them correctly).

It is to be noted that this problem does not affect the explicit only under the assumption that the signature OID and the key OIDs are the same, which it is something that is not always the case outside the explicit case.

In practice, this allows me to generate and store the parameters at the algorithm-signing level in the `SEQUENCE of digitalSignature` without having to get parameters from the ASN1 layer (which might not be used for generating non-X509 signatures).

Last but not least, the other change we might want to consider is making the `algorithm` field optional so that it makes it (almost) backward compatible with the previous use-case:
```
digitalSignature ::= SEQUENCE {
    algorithm         AlgorithmIdentifier   OPTIONAL,
    signature         BIT STRING
}
```
... but then, how do you convey the parameters for the inner signatures (e.g., RSA-PSS) or other possible combinations in the future?

**Comment by johngray-dev** [comment]
I don't understand why we would need or want to do this.   When CompositeParams is the following:

CompositeParams ::= SEQUENCE SIZE (2..MAX) OF AlgorithmIdentifier

Each algorithm Identifier component contains the parameters.   Why is that a problem?    That is how a single non-composite algorithm works today.   An algorithm like RSA-PSS that requires parameters would have the parameters encoded in its AlgorithmIdentifier as expected.   

I implemented composite as a signature algorithm, and I can sign anything I want, and verify it without a problem.  I need to know the AlgorithmID when I am verifying, and the parameters are in the algorithmID (if I need parameters), so why is that a problem?  If I have a raw RSA-PSS signature Bit String for a non-composite signature, I would have the same problem, I wouldn't have access to the parameters.   

So why would we want to change the signature format for composite when every other non-composite signature algorithm would have the same issue when given a raw signature blob to verify.  Maybe I don't understand something here?
