### ISSUE TITLE
Compact Composite keys format

### ISSUE THREAD

**Issue by johngray-dev** [EntrustCorporation/draft-ounsworth-composite-sigs#109]
Use a more compact keys format by removing redundancy which makes implementations a bit more difficult, but probably removes some more edge scenarios Tim is worried about.

Today we use:
subjectPublicKeyInfo ::= {
             algorithm AlgorithmIdentifier,	 
            subjectPublicKey    CompositeKey,
}

We want to change CompositeKey to the following:

CompositeKey ::= SEQUENCE OF OCTET STRING

instead of SEQUENCE of SubjectPublicKeyInfo...   So redundent subjectPublicKeyInfo information is now removed.

**Comment by ounsworth** [comment]
Done in -10
