### ISSUE TITLE
PSS salt and trailer len should be fixed per parameter set

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#114]
See RFC 4055 -- but that's based on SHA1, so we will need the salt len to be 32 bytes for a 256 bit hash), etc.

Trailer len remains DEFAULT 1.

**Comment by johngray-dev** [comment]
I believe this has been addressed in version -11 -  We use SHA256 for the MLDSA44 with RSA2048 combination, and SHA512 for the MLDSA65 with RSA 3072.

**Comment by johngray-dev** [comment]
As mentioned above, this was resolved in -11
