### ISSUE TITLE
Remove Falcon from Draft (formely - "Falcon" needs to be renamed to "FN-DSA")

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#117]
The -10 changelog says that we did this, but in fact we did not.

**Comment by johngray-dev** [comment]
I think that is okay.  NIST hasn't officially released FN-DSA (Though we have seen it referred to that way by NIST people).   Do we want to take Falcon out (for now) since it looks like it won't get standardized for another year or more?

**Comment by johngray-dev** [comment]
Group decided to remove FN-DSA and change title to "Composite ML-DSA for use in Internet PKI" (or something like that).

**Comment by johngray-dev** [comment]
This should be resolved in pull request #138

**Comment by johngray-dev** [comment]
Removed Falcon, reviewed with group.  Closing this issue.
