### ISSUE TITLE
Include a Security Consideration about Trust Anchors

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#118]
As Separability / Stripping Attack protection, we are placing a fair amount of weight on the fact that within PKIX, public keys are bound in certificates plus the MUST NOT in this draft about not re-using component public keys in non-composite public keys. That *should* be enough to prevent public key substitutions that lead to Separability attacks.

HOWEVER, we are aware of one case within PKIX where public keys can be used raw (ie not in a certificate): Trust Anchors as in RFC5914 where public keys appear in an unsigned structure. It should be the case that TAs are distributed in a way that does not allow tampering, and they too should respect the MUST NOT about transporting the component public keys independently, but it is probably worth mentioning explicitly in Security Considerations.

**Comment by johngray-dev** [comment]
We are expecting keys are bound to certificates, and the binding goes all the way to the root.

**Comment by johngray-dev** [comment]
Makes sense, here is a stab at some text.

This specification makes an assumption that composite public keys will be bound in a structure that contains a signature over the public key (for example, and X.509 Certificate), which is chained back to a trust anchor.  Without such a mechanism in place (such as RFC 5914), it is possible that the component keys can be separated without detection.   If a composite public key will appear in an unsigned structure, then they MUST be distributed in a way that prevents tampering.

**Comment by ounsworth** [comment]
Thanks for taking a shot John. Here's a v2 of that text:

> When considering stripping attacks, we need to consider the case where an attacker has fully compromised one of the component algorithms to the point that they can fully forge signatures from one of the component algorithms. This would allow them to construct malicious documents that carry a valid signature under one of the component public keys. The protection against this attack relies on the victim verifier only trusting the vulnerable public key in composite, and not trusting by itself.
> Specifically, in order to achieve this non-separability property, this specification makes two assumptions about how the verifier will establish trust in a composite public key. 1) All of the component keys within a composite key are freshly generated for the composite; ie a given public key MUST NOT appear as a component within a composite certificate and also within a single-algorithm certificate 2) We assume that composite public keys will be bound in a structure that contains a signature over the public key (for example, an X.509 Certificate), which is chained back to a trust anchor, and where that signature is at least as strong as the composite public key it is protecting. There are mechanisms within Internet PKI where trusted public keys do not appear within signed structures -- such as the Trust Anchor format defined in [RFC5914]. In such cases. In such cases, it is the responsibility of the implementer to ensure that trusted composite keys are distributed in a way that does not allow the component keys to be trusted independently.

I have not looked at how this flows with the rest of the Security Considerations, so you may need to adjust a bit for flow when you insert it.

**Comment by johngray-dev** [comment]
So you want to replace the text with all of this, or just the second paragraph first?   It uses 'we' in a number of places so I'm not sure if this is a suggestion to add some additional points, or if we just massage what you have in the more boring IETF draft voice.

**Comment by johngray-dev** [comment]
This issue was resolved by pull request #140
