### ISSUE TITLE
Resolve ASN.1 issue of OCTET_STRING mapping into BIT STRING for pk-composite type

### ISSUE THREAD

**Issue by johngray-dev** [EntrustCorporation/draft-ounsworth-composite-sigs#125]
pk-CompositeSignature {
        OBJECT IDENTIFIER:id, FirstPublicKeyType,
        SecondPublicKeyType} PUBLIC-KEY ::=
        {
          IDENTIFIER id
          KEY SEQUENCE {
           firstPublicKey BIT STRING (CONTAINING FirstPublicKeyType),
           secondPublicKey BIT STRING (CONTAINING SecondPublicKeyType)
          }
          PARAMS ARE absent
          CERT-KEY-USAGE { digitalSignature, nonRepudiation, keyCertSign, cRLSign }
        }

  pk-MLDSA44-RSA2048-PSS-SHA256 PUBLIC-KEY ::=
     pk-CompositeSignature{ id-MLDSA44-RSA2048-PSS-SHA256,
     OCTET STRING, RSAPublicKey}

**Comment by ounsworth** [comment]
I vote that we do this in -13 (ie this might be a breaking change, so leave it for -12, which is the version we'll do a Call For Adoption on).

**Comment by ounsworth** [comment]
draft-ietf-lamps-dilithium-certificates-03 says:

> The ML-DSA public key (a concatenation of rho and t1 that is an OCTET STRING) is mapped to a subjectPublicKey (a value of type BIT STRING) as follows: the most significant bit of the OCTET STRING value becomes the most significant bit of the BIT STRING value, and so on; the least significant bit of the OCTET STRING becomes the least significant bit of the BIT STRING.




This follows the strong tradition of doing the same unpacking for EC:

RFC5480:

The elliptic curve public key (a value of type ECPoint that is
        an OCTET STRING) is mapped to a subjectPublicKey (a value of
        type BIT STRING) as follows: the most significant bit of the
        OCTET STRING value becomes the most significant bit of the BIT
        STRING value, and so on; the least significant bit of the OCTET
        STRING becomes the least significant bit of the BIT STRING.
        Conversion routines are found in Sections 2.3.1 and 2.3.2 of
        [SEC1].


RFC8410:

PublicKey ::= BIT STRING

subjectPublicKey contains the byte stream of the public key.  The
      algorithms defined in this document always encode the public key
      as an exact multiple of 8 bits.


The way we have it defined in Composite;

```
firstPublicKey BIT STRING (CONTAINING FirstPublicKeyType),
```

means that we'll end up with a double-layer of type wrapping -- that BIT STRING will contain the DER encoding of whatever type we declare in FirstPublicKeyType.

I think we're gonna have to unroll that class into something like

~~~
pk-CompositeSignature-Untyped {
OBJECT IDENTIFIER:id} PUBLIC-KEY ::=
{
IDENTIFIER id
KEY SEQUENCE {
firstPublicKey BIT STRING,
secondPublicKey BIT STRING
}
PARAMS ARE absent
CERT-KEY-USAGE { digitalSignature, nonRepudiation, keyCertSign, cRLSign }
}

pk-CompositeSignature-MLDSA-RSA {
OBJECT IDENTIFIER:id,
SecondPublicKeyType} PUBLIC-KEY ::=
{
IDENTIFIER id
KEY SEQUENCE {
firstPublicKey BIT STRING,
secondPublicKey BIT STRING (CONTAINING RSAPublicKey)
}
PARAMS ARE absent
CERT-KEY-USAGE { digitalSignature, nonRepudiation, keyCertSign, cRLSign }
}
~~~

**Comment by johngray-dev** [comment]
I think I'm confused.  I think you are saying we are okay for ML-DSA and ECDSA because they have that mapping language.   I looked at the definition of SubjectPublicKeyInfo:

  SubjectPublicKeyInfo  ::=  SEQUENCE  {
        algorithm            AlgorithmIdentifier,
        **subjectPublicKey     BIT STRING**  }

RSA has this definition:
   RSAPublicKey  ::=  SEQUENCE  {
         modulus            INTEGER,    -- n
         publicExponent     INTEGER  }  -- e

So an RSAPublicKey as a BIT STRING will have a sequence identifier in there, but it won't be double wrapped, and it would be needed.   Where is the double wrapping coming from?  Maybe I am just missing something.  

So I would read the following:

pk-MLDSA44-RSA2048-PSS-SHA256 PUBLIC-KEY ::=
pk-CompositeSignature{ id-MLDSA44-RSA2048-PSS-SHA256,
OCTET STRING, RSAPublicKey}

As an MLDSA44-RSA2048 public key.   The identifier is the  id-MLDSA44-RSA2048-PSS-SHA256 and the first OCTET STRING (being ML-DSA) maps nicely to a BIT STRING based on the text you added from the dilithium draft, and the RSAPublicKey is a BIT String containing a Sequence of the two RSA components needed for an RSA Public Key.     

So I don't think we need to change anything here... ??

**Comment by johngray-dev** [comment]
Group agreed to look at this in more detail after version -13

**Comment by johngray-dev** [comment]
Team is agreeing we are encoding what we want to encode and it appears to comply with the ASN.1 and the way we have implemented it.
