### ISSUE TITLE
Remaining "two or more"s

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#128]
From Tim:

https://mailarchive.ietf.org/arch/msg/spasm/uGbyTbj1rr_4SnazNkhHrGDKeXA/

> * The 2.3 defines composite signature, it says “A composite signature 
> allows two *or more* underlying signature algorithms to be combined”. 
> The rest of the draft defines composite as combination of exactly 2 (i.e. definition in 4.2).
> I guess “or more” is just a typo, right? I mean, are there plans to 
> extend this draft, so that composite is made of more than 2 component 
> algorithms? From engineering point of view, it would be a major difference.

It's the other way around.  The "or more" is a vestige of older drafts that allowed more than two components.

The current draft is exactly two, which I personally think is exactly right.

**Comment by johngray-dev** [comment]
Kris had this comment as well, and it has been resolve.  The draft now says two (and not two or more).
