### ISSUE TITLE
Comments from Kris

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#129]
https://mailarchive.ietf.org/arch/msg/spasm/1z1i_2FrsjTrjCP7BytCi9ofDEY/

Hello,

After reading the draft-ounsworth-pq-composite-sigs-11 I have couple of questions/suggestions.

* Is there a document describing real-world use cases for this draft? I’m aware of draft-vaira-pquip-pqc-use-cases, but really I’m looking for use cases where draft-ounsworth-pq-composite-sigs will be clearly very useful/necessary to have.
* IMHO: the draft-hale-pquip-hybrid-signature-spectrums-01 provides good background info on composite/hybrid signatures. I find the classification of different types of non-separability (section 2.) very useful. May I suggest that draft-ounsworth-pq-composite-sigs mentions that work and explains that draft targets "weak non-separability”? That way users of implementations based on that draft will be well aware of security assumptions that they should expect.
* The 2.3 defines composite signature, it says “A composite signature allows two *or more* underlying signature algorithms to be combined”. The rest of the draft defines composite as combination of exactly 2 (i.e. definition in 4.2). I guess “or more” is just a typo, right? I mean, are there plans to extend this draft, so that composite is made of more than 2 component algorithms? From engineering point of view, it would be a major difference.
* Nit: The 2.3 says “A verification algorithm which takes as input a public key, a Message and signature and outputs true if the signature and public key can be used to verify the message”. Obviously, the goal of verify() is not only to check the key, but to use it to verify signature. I guess, the text should be slightly corrected to say “outputs true if signature verifies correctly”.

Kind regards,

-- 
Kris Kwiatkowski
Cryptography Dev

**Comment by johngray-dev** [comment]
Resolve comments in latest -13 version.
