### ISSUE TITLE
Should Sect 4 "Composite Structures" be explicit that it fits in existing fields?

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#20]
We mention above that this is compatible with existing fields in X.509 certificates, and other Public Key and Signatures structures. Do we need to be explicit about that in section 4?

**Comment by csosto-pk** [comment]
I think 
> We define encodings of sequences of public keys and signature data which consist of a sequence of public keys and signatures from more basic signature algorithms (aka "component algorithms") such that these structures can be placed into any existing public key or signature structure.

looks fine. These composite sigs and keys are going to be replace the existing fields, so there is nothing wrong with this sentence.
