### ISSUE TITLE
Add section "Implications For Existing Standards > CMS"

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#31]
This section will need to be added.

**Comment by ounsworth** [comment]
In an email, Dan said:

> I thought back to the digest vs pre-hash discussion for cms-hash-sigs on the LAMPS list and this made me think there may be issues to tackle in CMS so I dug a little deeper.  Here’s what I came up with.
> -	I’ll assume we don’t want to address key transport or key agreement using composite public keys in CMS.  If we did then we’d have to consider hybridization of the resulting shared secrets.  The draft could just focus on signature-related public keys.
> -	The SubjectKeyIdentifier object is used to identify the signer’s certificate.  This is the same as the subjectKeyIdentifier in an X.509 certificate so it would be treated similarly if discussed in the document.  It may be worth mentioning that this should be derived from the composite key and not one of the component keys.
> -	The OriginatorPublicKey object has the same structure as the SubjectPublicKeyInfo object in X.509 so the composite public key should be applied to it in the same way.  Possibly just a comment mentioning this could be useful.
> -	SignerInfo.digestAlgorithm identifies the message digest used by the signer.  This is the biggest concern for composite signatures, because each signature in the composite signature may use a different digest (e.g. ecdsa-with-SHA512 combined with id-alg-hss-lms-hash-sig).  Or were people thinking that each signature algorithm would be required to use the same digest (and then we’d have to define possibly multiple signature algorithm OIDs like id-alg-composite-with-SHA512, etc)?  If the composite signature’s digest type is “intrinsic” (i.e. each component uses their own digest) then we may need a CompositeDigest algorithm identifier where its parameters are a SEQUENCE of the components DigestAlgorithmIdentifiers.

>Thanks,
>Dan

**Comment by ounsworth** [comment]
> I think this can be used to inform whether we need an "implications for other standards -CMS" section or something like in Max's draft which was actually defining the behaviour for CMS (if there's actually a difference between those options).

**Comment by danvangeest** [comment]
Also, https://tools.ietf.org/html/rfc6211 addresses an algorithm substitution attack by copying the digest + signature algorithm fields into the signed attributes.  If a composite signature introduces multiple digests, do they need to be included in the digest field so they can be copied into the signed attributes?  (or maybe it's already taken care of by copying the signature algorithm field?)

**Comment by ounsworth** [comment]
We have since removed the whole section.
