### ISSUE TITLE
Reference implementation Phase1: produce composite cert files

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#36]
For this, we can use existing algorithms (RSA + ECC, or RSA2048 + RSA4096).

**Comment by ounsworth** [comment]
I would be best if we can get multi-vendor interop on these PoCs ... ie Entrust, Cisco, CableLabs, DigiCert? each make one independently .. ?

**Comment by csosto-pk** [comment]
> I would be best if we can get multi-vendor interop on these PoCs ... ie Entrust, Cisco, CableLabs, DigiCert? each make one independently .. ?

Yes. Some might choose to enhanse existing libraries. For example Cisco would prefer to enhance OpenSSL to do the interop. Other vendors may chose to use their own code. And they don't always have to open-source their code. Reference implementations are useful, but not a must for IETF.

**Comment by henrydcase** [comment]
PQShield is interested in interop. We are mainly interested in using combo of classical+PQ algorithms, but for phase 1 we could have implementation of classical+classical. Is it "RSA2048 + RSA4096" that will be used for that?

**Comment by ounsworth** [comment]
@henrydcase classical+PQ is certainly the end-goal. The idea of doing interop on RSA2048+RSA4096 is so we can test composite in isolation from needing to plug in compatible versions of PQ algs.

For example, my test tool implementation of this draft is on java without any PQ algs plugged in.

**Comment by henrydcase** [comment]
@ounsworth yep, fully understood. Just asking to make sure we do same selection for classical algorithms for interop testing.

**Comment by johngray-dev** [comment]
This is essentially what we have been doing with our IETF hackathon.   See https://github.com/IETF-Hackathon/pqc-certificates
