### ISSUE TITLE
Is Max's section "Asymmetric Key Packages" redundant with our definitions of things?

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#46]
Reminder to come back to this because I'm too tired to think this through at the moment, so I'm just copying his text verbatim.

It seems like this section is saying the same thing that we do when defining composite public keys and signatures.

**Comment by henrydcase** [comment]
It seems to me that there are some contradicting parts actually:

```
In 2.4. 
AlgorithmIdentifier for a composite public key MUST use the id-alg-composite
```
in 4.2
the privateKeyAlgorithm in the OneAsymmetricKey SHALL be set to id-alg-composite.
```

but indeed, it seems to be redundant.
