### ISSUE TITLE
Mention potential implementation gotchas for unknown component algorithm types

### ISSUE THREAD

**Issue by danvangeest** [EntrustCorporation/draft-ounsworth-composite-sigs#55]
We allow some component algorithms to be unknown, but ASN.1 parsers that I have experienced will will return an error immediately when encountering an unknown AlgorithmIdentifier OID.  When parsing a CompositePublicKey or CompositeParams object, an implementer should be careful to check for this error and allow parsing to continue so that a later policy check can determine whether the recognized algorithms are sufficient for the policy.  They should however handle other errors encountered during the AlgorithmIdentifier parsing (e.g. invalid length) as they would normally.

Add some text indicating this should be an implementation concern.

**Comment by csosto-pk** [comment]
Not sure this is necessary. Many of the RFCs that define new OIDs don't add text about such implementation problems. An example is where I say 

```
   Conforming CA implementations MUST specify the X.509 public key
   algorithm explicitly by using the OIDs specified in Section 4 when
   encoding ECDSA with SHAKE public keys in certificates and CRLs.
   Conforming client implementations that process ECDSA with SHAKE
   public keys when processing certificates and CRLs MUST recognize the
   corresponding OIDs.
```
The draft is in AD Review and WGLC, and I have heard any objections. 

Such language could be useful but I think the more text we add the more complicated we become.

**Comment by johngray-dev** [comment]
This is no longer relevant since we heard from IETF that generic is the way to go.  Closing.
