### ISSUE TITLE
Do we need an Composite Algorithm OID for keys and a composite OID for Signatures?

### ISSUE THREAD

**Issue by jogray72** [EntrustCorporation/draft-ounsworth-composite-sigs#92]
As part of implementing the specification, I came across this difficult.

In one part of the draft it says the following:

2.2  Composite Keys

   A composite key is a single key object that performs an atomic
   signature or verification operation, using its encapsulated sequence
   of component keys.

   The ASN.1 algorithm object for composite public and private keys is:

   pk-Composite PUBLIC-KEY ::= {
       **IDENTIFIER id-alg-composite**
       KEY CompositePublicKey
       PARAMS ARE absent
       CERT-KEY-USAGE
           { digitalSignature, nonRepudiation, keyCertSign, cRLSign }
       PRIVATE-KEY CompositePrivateKey
   }

So The AlgorithmID does not have Parameters,

Then later for Composite Signature:

Composite Signature

   The ASN.1 algorithm object for a composite signature is:

   sa-CompositeSignature SIGNATURE-ALGORITHM ::= {
       **IDENTIFIER id-alg-composite**
       VALUE CompositeSignatureValue
       PARAMS TYPE CompositeParams ARE required
       PUBLIC-KEYS { pk-Composite }
       SMIME-CAPS { IDENTIFIED BY id-alg-composite } }
   }

So when implementing I used the first one that didn't have parms, and when I used the second one in the Signature it didn't have parameters.   Obviously that caused problems.   So I am wondering if the Composite structure OID that has absent parameters should have one OID value, and the one for keys should have a different value?   Then it would be easier to differentiate between the CompositeOID container OID verses the Key OID which requires parameters.

So Maybe we define something like:

 id-alg-composite-key OBJECT IDENTIFIER ::= {
       iso(1) identified-organization(3) dod(6) internet(1) security(5)
       mechanisms(5) pkix(7) algorithms(6) composite(??) key (1)}

Which MUST have absent parameters, then the remaining id-alg-composite must have Composite params.    Or to be more clear, we could change it to id-alg-composite-sig

**Comment by danvangeest** [comment]
This is a good question, and we may want input from an ASN.1 expert (I'm definitely an expert, though if you or anyone else here is then I'd defer to you.  I had just written those ASN.1 definitions based off other examples I'd seen).

The closest I've found is PSS ([RFC 5912](https://tools.ietf.org/html/rfc5912)) where the public key has optional parameters and the signature has required parameters.
```
   --
   -- Public key object for PSS signatures
   --

pk-rsaSSA-PSS PUBLIC-KEY ::= {
       IDENTIFIER id-RSASSA-PSS
       KEY RSAPublicKey
       PARAMS TYPE RSASSA-PSS-params ARE optional
        -- Private key format not in this module --
       CERT-KEY-USAGE { nonRepudiation, digitalSignature,
                            keyCertSign, cRLSign }
   }

   --
   --  Signature algorithm definition for PSS signatures
   --

   sa-rsaSSA-PSS SIGNATURE-ALGORITHM ::= {
       IDENTIFIER id-RSASSA-PSS
       PARAMS TYPE RSASSA-PSS-params ARE required
       HASHES { mda-sha1 | mda-sha224 | mda-sha256 | mda-sha384
                    | mda-sha512 }
       PUBLIC-KEYS { pk-rsa | pk-rsaSSA-PSS }
       SMIME-CAPS { IDENTIFIED BY id-RSASSA-PSS }
   }
```

I also came across Ed25519 ([RFC 8410](https://tools.ietf.org/html/rfc8410)) where the same identifier is used for both the public key and the signature.  And of course there's the well known `id-ecPublicKey` and `ecdsa-with-SHA256` identifier combinations.

None of these map perfectly to our situation, although I wonder if doing it the PSS way (making the parameters optional in the public key) would help out with implementation.  @jogray72 if you were to think about how you would implement PSS, would you come across similar problems due to the params being optional in the PK but required in the SA?

I don't necessarily object to defining separate `-key` and `-sig` identifiers, I'm just trying to think through what would be the cleanest way to handle this.

Another more extreme change would be to make the params required in the PK:
```
   pk-Composite PUBLIC-KEY ::= {
       IDENTIFIER id-alg-composite
       KEY CompositePublicKey
       PARAMS TYPE CompositeParams ARE required
       CERT-KEY-USAGE
           { digitalSignature, nonRepudiation, keyCertSign, cRLSign }
       PRIVATE-KEY CompositePrivateKey
   }
```
and then either duplicating the params in the SPKIs of the `CompositePublicKey` as it's currently defined:
```
CompositePublicKey ::= SEQUENCE SIZE (1..MAX) OF SubjectPublicKeyInfo
```
or removing the identifiers from `CompositePublicKey`:
```
CompositePublicKey ::= SEQUENCE SIZE (1..MAX) OF BIT STRING
```
I think we had discussed previously that it would be good to keep `SubjectPublicKeyInfo` in `CompositePublicKey` to make implementation easier, @jogray72 perhaps you could comment on this now that you're doing the implementation?

Regardless of which way we go, it would probably be valuable to add a note for the WG asking if the way we choose is best or if there's a better way.

**Comment by csosto-pk** [comment]
Recently, we used the same OIDs for SHAKES in CMS and SHAKES in X.509. 
See sections 4.2 in https://tools.ietf.org/html/rfc8692 and 3.3 in https://tools.ietf.org/html/rfc8702 

No need for a separate OIDs

**Comment by danvangeest** [comment]
> Recently, we used the same OIDs for SHAKES in CMS and SHAKES in X.509.
> See sections 4.2 in https://tools.ietf.org/html/rfc8692 and 3.3 in https://tools.ietf.org/html/rfc8702
> 
> No need for a separate OIDs

Are you referring to the `id-RSASSA-PSS-SHAKE256` (and 128 variant) OIDs?  I'm not sure that they map to the problem here because for both the associated `PUBLIC-KEY` and `SIGNATURE-ALGORITHM` definitions the params are defined as absent, unlike the current definition for the composite OID.

**Comment by csosto-pk** [comment]
> > Recently, we used the same OIDs for SHAKES in CMS and SHAKES in X.509.
> > See sections 4.2 in https://tools.ietf.org/html/rfc8692 and 3.3 in https://tools.ietf.org/html/rfc8702
> > No need for a separate OIDs
> 
> Are you referring to the `id-RSASSA-PSS-SHAKE256` (and 128 variant) OIDs? I'm not sure that they map to the problem here because for both the associated `PUBLIC-KEY` and `SIGNATURE-ALGORITHM` definitions the params are defined as absent, unlike the current definition for the composite OID.

Initially we used to define parameters but as the drafts progressed we ended up hardcoding them. The idea is that when you have that OID you practically will know what algorithms and their parameters are included in the public key or signature. And then you just parse them. This draft will inevitably define OIDs in the end, so we could follow the same paradigm, I think.

**Comment by jogray72** [comment]
Thanks for the comments.   The current implementation I have does use the same OID and it works, but I think it makes sense to make a distinction between signature parameters and key parameters.  Some algorithms like EC have key parameters, some algorithms like RSAPSS have signature parameters.   In the case of composite keys we are wrapping components that may contain their own key parameters which are encapsulated by the AlgorithmID parameters of each component.   So I don't think the way we are using keys in composite need parameters (at least not yet).   

 However, for the composite signature, there needs to be a way to tell the signature validation component what algorithms as being validated, so the parameters have to be there.   I ran into this problem when I expanded signature validation to work with keys other than RSA and EC.  I would determine the component signature validation by looking at the type of key.  However, for something like SPHINCS that wasn't possible because the component implementation of SPHINCS I tested with (from Bouncy Castle) the name in the Key did not map to the Signature algorithm.   Thus I had to fudge it by hardcoding a mapping from the SPHINCS key type to the Signature type.   So it became clear I wasn't encoding the signature parameters correctly.  

So I think having a composite key OID (which can be used for both public and private keys), and a Composite Signature OID makes things more clear.   Also, with the Signature OID, the parameters could include more than just the components.  If we wanted to encode special validation instructions or modes (like all keys, or 1 key, or something else), it could be done through the Composite signature parameters.   

Right now our Signature parameters are defined as follows:  

CompositeParams ::= SEQUENCE SIZE (1..MAX) OF AlgorithmIdentifier

So it could be expanded a bit to something like this:

CompositeSignatureParams ::=  SEQUENCE  {
      compositeParams  CompositeParams,
     [0] <TBD> other stuff (like an AlgorithmIdentifier for example)...
}

Thoughts?

**Comment by ounsworth** [comment]
I have made separate OIDs.

[draft-ounsworth-pq-composite-keys.txt](https://raw.githubusercontent.com/EntrustCorporation/draft-ounsworth-pq-composite-keys/master/draft-ounsworth-pq-composite-keys.txt):

    id-composite-key OBJECT IDENTIFIER ::= {
    joint-iso-itu-t(2) country(16) us(840) organization(1) entrust(114027) Algorithm(80) Composite(4) CompositeKey(1) }

and

[draft-ounsworth-pq-composite-sigs.txt](https://github.com/EntrustCorporation/draft-ounsworth-composite-sigs/blob/only_sigs/draft-ounsworth-pq-composite-sigs.txt):

     id-alg-composite OBJECT IDENTIFIER ::= {
       iso(1)  identified-organization(3) dod(6) internet(1) private(4)
       enterprise(1) OpenCA(18227) Algorithms(2) id-alg-composite(1) }
